#!/usr/bin/env python3
# -*- mode: python -*-

import sys

# FIXME: need to rig something up so I can easily run this from inside the
#        source tree (i.e., w/out installing)
sys.path.append("modules")
import srp.cli

# FIXME: should i catch exceptions from main or just let it handle things
#        itself?
#
#try:
#    srp.cli.main()
#except Exception as e:
#    print("ERROR: %s" % e)
#    sys.exit(1)
#sys.exit(0)

srp.cli.main()
