#!/usr/bin/env python3
# -*- mode: python -*-

import os
import sys

# This is so we can find our module in the source tree during development.
# Our install target sed's this conditional into oblivion.
if "__DEV__":
    sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), "modules"))

import srp

# FIXME: should i catch exceptions from main or just let it handle things
#        itself?
#
#try:
#    srp.cli.main()
#except Exception as e:
#    print("ERROR: %s" % e)
#    sys.exit(1)
#sys.exit(0)

srp.cli.main()

# FIXME: make sure we only do this if we're exiting cleanly
#
#        only install, uninstall, and maybe action should do this
#srp.db.commit()
