#!/usr/bin/env python3
# -*- mode: python -*-

import sys

sys.path.append("dev-3.0")
import srp.cli

try:
    srp.cli.main()
except Exception(e):
    print("ERROR: %s" %e)
    sys.exit(1)
sys.exit(0)
